// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0B-YvYI2zIsptwC_vzoW4M6qYDvgkRm8',
    appId: '1:401968948400:web:df7df894c8b13a0469c775',
    messagingSenderId: '401968948400',
    projectId: 'productauthfb',
    authDomain: 'productauthfb.firebaseapp.com',
    storageBucket: 'productauthfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zE9YkiyEyQr38jbB5_ig0HJtzPXdios',
    appId: '1:401968948400:android:1873bea1e6e0f9e369c775',
    messagingSenderId: '401968948400',
    projectId: 'productauthfb',
    storageBucket: 'productauthfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS9g91yFTr8BkjOPtuRBQMvPpWShQXPb0',
    appId: '1:401968948400:ios:6bd5e7b9c68bf13269c775',
    messagingSenderId: '401968948400',
    projectId: 'productauthfb',
    storageBucket: 'productauthfb.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS9g91yFTr8BkjOPtuRBQMvPpWShQXPb0',
    appId: '1:401968948400:ios:6bd5e7b9c68bf13269c775',
    messagingSenderId: '401968948400',
    projectId: 'productauthfb',
    storageBucket: 'productauthfb.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0B-YvYI2zIsptwC_vzoW4M6qYDvgkRm8',
    appId: '1:401968948400:web:e2190891ded4c5b069c775',
    messagingSenderId: '401968948400',
    projectId: 'productauthfb',
    authDomain: 'productauthfb.firebaseapp.com',
    storageBucket: 'productauthfb.appspot.com',
  );
}
